"""empty message

Revision ID: 5a9e81887e81
Revises: 
Create Date: 2024-10-23 11:37:30.980329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a9e81887e81'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('houses', schema=None) as batch_op:
        batch_op.drop_column('listed_date')
        batch_op.drop_column('latitude')
        batch_op.drop_column('house_type')
        batch_op.drop_column('longitude')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('houses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('longitude', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('house_type', sa.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('latitude', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('listed_date', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
