"""Add active field to User model

Revision ID: b1900fd73fb1
Revises: 70a893b87144
Create Date: 2024-10-29 17:49:06.181393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1900fd73fb1'
down_revision = '70a893b87144'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('houses', schema=None) as batch_op:
        batch_op.drop_column('listed_date')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('active')

    with op.batch_alter_table('houses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('listed_date', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
